// <auto-generated />
using System;
using CafeEase.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeEase.Services.Migrations
{
    [DbContext(typeof(CafeEaseDbContext))]
    partial class CafeEaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeEase.Services.Database.Cafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Cafes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Titova 12",
                            CityId = 1,
                            IsActive = true,
                            Latitude = 43.856299999999997,
                            Longitude = 18.4131,
                            Name = "CafeEase Centar",
                            PhoneNumber = "+38761111222",
                            WorkingHours = "08:00 - 23:00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bravadziluk 8",
                            CityId = 1,
                            IsActive = true,
                            Latitude = 43.859499999999997,
                            Longitude = 18.433499999999999,
                            Name = "CafeEase Bascarsija",
                            PhoneNumber = "+38761111333",
                            WorkingHours = "08:00 - 22:00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Vrbanja 1",
                            CityId = 1,
                            IsActive = true,
                            Latitude = 43.854900000000001,
                            Longitude = 18.403300000000002,
                            Name = "CafeEase SCC",
                            PhoneNumber = "+38761111444",
                            WorkingHours = "09:00 - 23:00"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mostarskog bataljona 21",
                            CityId = 2,
                            IsActive = true,
                            Latitude = 43.343800000000002,
                            Longitude = 17.8078,
                            Name = "CafeEase Mostar",
                            PhoneNumber = "+38761111555",
                            WorkingHours = "08:00 - 23:00"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Marsala Tita 20",
                            CityId = 3,
                            IsActive = true,
                            Latitude = 44.538400000000003,
                            Longitude = 18.667100000000001,
                            Name = "CafeEase Tuzla",
                            PhoneNumber = "+38761111666",
                            WorkingHours = "07:30 - 22:30"
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cold Drinks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Energy drinks"
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tuzla"
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.LoyaltyPoints", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoyaltyPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Points = 51,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Points = 15,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2026, 4, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            TableId = 2,
                            TotalAmount = 14.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2026, 4, 18, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TableId = 1,
                            TotalAmount = 7.00m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2026, 4, 19, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            TableId = 4,
                            TotalAmount = 9.20m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2026, 4, 19, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            TableId = 5,
                            TotalAmount = 12.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MilkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SugarLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 2.50m,
                            ProductId = 1,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 2,
                            Note = "Less sweet",
                            OrderId = 1,
                            Price = 4.00m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            Price = 3.50m,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            Price = 3.20m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            Price = 3.00m,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            MilkType = "Oat",
                            Note = "Extra hot",
                            OrderId = 3,
                            Price = 3.00m,
                            ProductId = 2,
                            Quantity = 1,
                            Size = "L",
                            SugarLevel = 2
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            Price = 6.00m,
                            ProductId = 7,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Method = "Card",
                            OrderId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Method = "Card",
                            OrderId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Method = "Cash",
                            OrderId = 4,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImagePath = "espresso.jpg",
                            Name = "Espresso",
                            Price = 2.5m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImagePath = "cappuccino.jpg",
                            Name = "Cappuccino",
                            Price = 3.0m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImagePath = "latte.jpg",
                            Name = "Latte",
                            Price = 3.20m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ImagePath = "icedcoffee.jpg",
                            Name = "Ice Coffee",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            ImagePath = "cheesecake.jpg",
                            Name = "Cheesecake",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ImagePath = "fanta.jpg",
                            Name = "Fanta",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            ImagePath = "red_bull.jpg",
                            Name = "Red bull",
                            Price = 6.00m
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetSegment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "10% off coffee products in the morning.",
                            DiscountPercent = 10.0,
                            EndDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Morning Coffee Deal",
                            StartDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetSegment = "ALL"
                        },
                        new
                        {
                            Id = 2,
                            Description = "15% off desserts on weekends.",
                            DiscountPercent = 15.0,
                            EndDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dessert Weekend",
                            StartDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetSegment = "VIP"
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.PromotionCategory", b =>
                {
                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("PromotionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PromotionCategories");

                    b.HasData(
                        new
                        {
                            PromotionId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            PromotionId = 2,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedProductId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfGuests = 2,
                            ReservationDateTime = new DateTime(2026, 4, 21, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            TableId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            NumberOfGuests = 2,
                            ReservationDateTime = new DateTime(2026, 4, 22, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TableId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            NumberOfGuests = 4,
                            ReservationDateTime = new DateTime(2026, 4, 24, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TableId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            NumberOfGuests = 4,
                            ReservationDateTime = new DateTime(2026, 4, 26, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            TableId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent espresso!",
                            DateCreated = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Good, but I’d like a bit more ice.",
                            DateCreated = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Cheesecake is great.",
                            DateCreated = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Rating = 5,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobile"
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            IsOccupied = false,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            IsOccupied = false,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 5,
                            IsOccupied = false,
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10,
                            IsOccupied = false,
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 8,
                            IsOccupied = false,
                            Number = 5
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Email = "admin@cafeease.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            PasswordHash = "L0uD9aDjQiZ6US9mT63C+tMvcSk=",
                            PasswordSalt = "js30TX4cHnStZnZM8pWbcg==",
                            RoleId = 1,
                            Username = "desktop"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Email = "mobileuser@cafeease.com",
                            FirstName = "Mobile",
                            LastName = "User",
                            PasswordHash = "w6NEGcaz3XwZej0uJcY1mJIWrAI=",
                            PasswordSalt = "tNcmHa/vi33ilAmQImsPhg==",
                            RoleId = 2,
                            Username = "mobile"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Email = "test@cafeease.com",
                            FirstName = "Test",
                            LastName = "User",
                            PasswordHash = "dlKlLumk23Dx2D3OgAiBbZsFmfo=",
                            PasswordSalt = "ym5obohaOyqCOlyuhaGxGQ==",
                            RoleId = 2,
                            Username = "test"
                        });
                });

            modelBuilder.Entity("CafeEase.Services.Database.Cafe", b =>
                {
                    b.HasOne("CafeEase.Services.Database.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Inventory", b =>
                {
                    b.HasOne("CafeEase.Services.Database.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("CafeEase.Services.Database.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CafeEase.Services.Database.LoyaltyPoints", b =>
                {
                    b.HasOne("CafeEase.Services.Database.User", "User")
                        .WithOne("LoyaltyPoints")
                        .HasForeignKey("CafeEase.Services.Database.LoyaltyPoints", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Notification", b =>
                {
                    b.HasOne("CafeEase.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Order", b =>
                {
                    b.HasOne("CafeEase.Services.Database.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeEase.Services.Database.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeEase.Services.Database.OrderItem", b =>
                {
                    b.HasOne("CafeEase.Services.Database.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeEase.Services.Database.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Payment", b =>
                {
                    b.HasOne("CafeEase.Services.Database.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Product", b =>
                {
                    b.HasOne("CafeEase.Services.Database.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CafeEase.Services.Database.PromotionCategory", b =>
                {
                    b.HasOne("CafeEase.Services.Database.Category", "Category")
                        .WithMany("PromotionCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeEase.Services.Database.Promotion", "Promotion")
                        .WithMany("PromotionCategories")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Reservation", b =>
                {
                    b.HasOne("CafeEase.Services.Database.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeEase.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Review", b =>
                {
                    b.HasOne("CafeEase.Services.Database.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeEase.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CafeEase.Services.Database.User", b =>
                {
                    b.HasOne("CafeEase.Services.Database.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeEase.Services.Database.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PromotionCategories");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Product", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Promotion", b =>
                {
                    b.Navigation("PromotionCategories");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CafeEase.Services.Database.Table", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CafeEase.Services.Database.User", b =>
                {
                    b.Navigation("LoyaltyPoints");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
